### ISSUE TITLE
autoAcceptor prevents clean shutdown of Network object

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/P2P-Platform#5]
Since the call to self.server.accept() is blocking, autoAcceptor doesn't return until a connection is accepted. That means that thread won't die when we set autoPoll to False until one final incoming connection is received.

**Comment by mpavlak2018** [comment]
I think fixing this to still try to use timers instead of our own threads will be challenging. We could set the sockets to non-blocking, but then we probably have to change a whole lot of network (including all recv send connect etc—I'd have to check specifics though) We could also try to figure out how to use interrupts (I think), but that sounds as bad as making our own threads again, and probably less neat... Do you want to consider keeping some level of definition of threads (maybe NetworkThreads), but just not for interface?

**Comment by jorndorff** [comment]
Yeah, I'm starting to think my whole timer idea was half-baked.

But what I still don't understand is how this wasn't an issue when we wrote a custom thread. That to `accept` was still blocking.

**Comment by jorndorff** [comment]
Actually, is it just a matter of using Daemon threads? I wonder when we lost track of that.

https://stackoverflow.com/a/190017/4184410

**Comment by jorndorff** [comment]
This is fixed as of 5640b73efbd994e46d5e442fa702d07535eb457e
